const initialTileState = {
  tile0: false,
  tile1: false,
  tile2: false,
  tile3: false,
  tile4: false,
  tile5: false,
  tile6: false,
  tile7: false,
  tile8: false,
  tile9: false,
  tile10: false,
  tile11: false,
  tile12: false,
  tile13: false,
  tile14: false,
  tile15: false,
  tile16: false,
  tile17: false,
  tile18: false,
  tile19: false,
  tile20: false,
  tile21: false,
  tile22: false,
  tile23: false,
  tile24: false,
}

export default initialTileState