const initialTileState = {
  tile0: "red",
  tile1: "red",
  tile2: "red",
  tile3: "red",
  tile4: "red",
  tile5: "red",
  tile6: "red",
  tile7: "red",
  tile8: "red",
  tile9: "red",
  tile10: "red",
  tile11: "red",
  tile12: "red",
  tile13: "red",
  tile14: "red",
  tile15: "red",
  tile16: "red",
  tile17: "red",
  tile18: "red",
  tile19: "red",
  tile20: "red",
  tile21: "red",
  tile22: "red",
  tile23: "red",
  tile24: "red",
}

export default initialTileState